/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArtifactsIndexRouteImport } from './routes/artifacts/index'
import { Route as ScrapsScrapIdRouteImport } from './routes/scraps/$scrapId'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as ArtifactsNewRouteImport } from './routes/artifacts/new'
import { Route as ArtifactsArtifactIdRouteImport } from './routes/artifacts/$artifactId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtifactsIndexRoute = ArtifactsIndexRouteImport.update({
  id: '/artifacts/',
  path: '/artifacts/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScrapsScrapIdRoute = ScrapsScrapIdRouteImport.update({
  id: '/scraps/$scrapId',
  path: '/scraps/$scrapId',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtifactsNewRoute = ArtifactsNewRouteImport.update({
  id: '/artifacts/new',
  path: '/artifacts/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtifactsArtifactIdRoute = ArtifactsArtifactIdRouteImport.update({
  id: '/artifacts/$artifactId',
  path: '/artifacts/$artifactId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/artifacts/$artifactId': typeof ArtifactsArtifactIdRoute
  '/artifacts/new': typeof ArtifactsNewRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/scraps/$scrapId': typeof ScrapsScrapIdRoute
  '/artifacts': typeof ArtifactsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/artifacts/$artifactId': typeof ArtifactsArtifactIdRoute
  '/artifacts/new': typeof ArtifactsNewRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/scraps/$scrapId': typeof ScrapsScrapIdRoute
  '/artifacts': typeof ArtifactsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/artifacts/$artifactId': typeof ArtifactsArtifactIdRoute
  '/artifacts/new': typeof ArtifactsNewRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/scraps/$scrapId': typeof ScrapsScrapIdRoute
  '/artifacts/': typeof ArtifactsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/profile'
    | '/search'
    | '/settings'
    | '/signup'
    | '/artifacts/$artifactId'
    | '/artifacts/new'
    | '/demo/tanstack-query'
    | '/scraps/$scrapId'
    | '/artifacts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/profile'
    | '/search'
    | '/settings'
    | '/signup'
    | '/artifacts/$artifactId'
    | '/artifacts/new'
    | '/demo/tanstack-query'
    | '/scraps/$scrapId'
    | '/artifacts'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/profile'
    | '/search'
    | '/settings'
    | '/signup'
    | '/artifacts/$artifactId'
    | '/artifacts/new'
    | '/demo/tanstack-query'
    | '/scraps/$scrapId'
    | '/artifacts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  ArtifactsArtifactIdRoute: typeof ArtifactsArtifactIdRoute
  ArtifactsNewRoute: typeof ArtifactsNewRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  ScrapsScrapIdRoute: typeof ScrapsScrapIdRoute
  ArtifactsIndexRoute: typeof ArtifactsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artifacts/': {
      id: '/artifacts/'
      path: '/artifacts'
      fullPath: '/artifacts'
      preLoaderRoute: typeof ArtifactsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scraps/$scrapId': {
      id: '/scraps/$scrapId'
      path: '/scraps/$scrapId'
      fullPath: '/scraps/$scrapId'
      preLoaderRoute: typeof ScrapsScrapIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artifacts/new': {
      id: '/artifacts/new'
      path: '/artifacts/new'
      fullPath: '/artifacts/new'
      preLoaderRoute: typeof ArtifactsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artifacts/$artifactId': {
      id: '/artifacts/$artifactId'
      path: '/artifacts/$artifactId'
      fullPath: '/artifacts/$artifactId'
      preLoaderRoute: typeof ArtifactsArtifactIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  ArtifactsArtifactIdRoute: ArtifactsArtifactIdRoute,
  ArtifactsNewRoute: ArtifactsNewRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  ScrapsScrapIdRoute: ScrapsScrapIdRoute,
  ArtifactsIndexRoute: ArtifactsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
